import re
from pathlib import Path

MAIN_COLUMNS = tuple(
    """
    CASE_NUMBER CASE_STATUS RECEIVED_DATE DECISION_DATE ORIGINAL_CERT_DATE
    VISA_CLASS JOB_TITLE SOC_CODE SOC_TITLE FULL_TIME_POSITION BEGIN_DATE END_DATE
    TOTAL_WORKER_POSITIONS NEW_EMPLOYMENT CONTINUED_EMPLOYMENT
    CHANGE_PREVIOUS_EMPLOYMENT NEW_CONCURRENT_EMPLOYMENT CHANGE_EMPLOYER
    AMENDED_PETITION EMPLOYER_NAME TRADE_NAME_DBA EMPLOYER_ADDRESS1
    EMPLOYER_ADDRESS2 EMPLOYER_CITY EMPLOYER_STATE EMPLOYER_POSTAL_CODE
    EMPLOYER_COUNTRY EMPLOYER_PROVINCE EMPLOYER_PHONE EMPLOYER_PHONE_EXT
    NAICS_CODE EMPLOYER_POC_LAST_NAME EMPLOYER_POC_FIRST_NAME
    EMPLOYER_POC_MIDDLE_NAME EMPLOYER_POC_JOB_TITLE EMPLOYER_POC_ADDRESS1
    EMPLOYER_POC_ADDRESS2 EMPLOYER_POC_CITY EMPLOYER_POC_STATE
    EMPLOYER_POC_POSTAL_CODE EMPLOYER_POC_COUNTRY EMPLOYER_POC_PROVINCE
    EMPLOYER_POC_PHONE EMPLOYER_POC_PHONE_EXT EMPLOYER_POC_EMAIL
    AGENT_REPRESENTING_EMPLOYER AGENT_ATTORNEY_LAST_NAME
    AGENT_ATTORNEY_FIRST_NAME AGENT_ATTORNEY_MIDDLE_NAME
    AGENT_ATTORNEY_ADDRESS1 AGENT_ATTORNEY_ADDRESS2 AGENT_ATTORNEY_CITY
    AGENT_ATTORNEY_STATE AGENT_ATTORNEY_POSTAL_CODE AGENT_ATTORNEY_COUNTRY
    AGENT_ATTORNEY_PROVINCE AGENT_ATTORNEY_PHONE AGENT_ATTORNEY_PHONE_EXT
    AGENT_ATTORNEY_EMAIL_ADDRESS LAWFIRM_NAME_BUSINESS_NAME
    STATE_OF_HIGHEST_COURT NAME_OF_HIGHEST_STATE_COURT WORKSITE_WORKERS
    SECONDARY_ENTITY SECONDARY_ENTITY_BUSINESS_NAME WORKSITE_ADDRESS1
    WORKSITE_ADDRESS2 WORKSITE_CITY WORKSITE_COUNTY WORKSITE_STATE
    WORKSITE_POSTAL_CODE WAGE_RATE_OF_PAY_FROM WAGE_RATE_OF_PAY_TO
    WAGE_UNIT_OF_PAY PREVAILING_WAGE PW_UNIT_OF_PAY PW_TRACKING_NUMBER
    PW_WAGE_LEVEL PW_OES_YEAR PW_OTHER_SOURCE PW_OTHER_YEAR
    PW_SURVEY_PUBLISHER PW_SURVEY_NAME TOTAL_WORKSITE_LOCATIONS
    AGREE_TO_LC_STATEMENT H_1B_DEPENDENT WILLFUL_VIOLATOR SUPPORT_H1B
    STATUTORY_BASIS APPENDIX_A_ATTACHED PUBLIC_DISCLOSURE
    PREPARER_LAST_NAME PREPARER_FIRST_NAME PREPARER_MIDDLE_INITIAL
    PREPARER_BUSINESS_NAME PREPARER_EMAIL EMPLOYER_FEIN
    LAWFIRM_BUSINESS_FEIN
    """.split()
)

WORKSITE_COLUMNS = tuple(
    """
    CASE_NUMBER WORKSITE_WORKERS SECONDARY_ENTITY SECONDARY_ENTITY_BUSINESS_NAME
    WORKSITE_ADDRESS1 WORKSITE_ADDRESS2 WORKSITE_CITY WORKSITE_COUNTY
    WORKSITE_STATE WORKSITE_POSTAL_CODE WAGE_RATE_OF_PAY_FROM
    WAGE_RATE_OF_PAY_TO WAGE_UNIT_OF_PAY PREVAILING_WAGE PW_UNIT_OF_PAY
    PW_TRACKING_NUMBER PW_WAGE_LEVEL PW_OES_YEAR PW_OTHER_SOURCE
    PW_OTHER_YEAR PW_SURVEY_PUBLISHER PW_SURVEY_NAME
    """.split()
)

HEADER_ALIASES = {"H-1B_DEPENDENT": "H_1B_DEPENDENT"}
COLUMNS = {"main": MAIN_COLUMNS, "worksites": WORKSITE_COLUMNS}


def map_headers(kind: str, headers: tuple[str, ...], path: Path) -> tuple[str, ...]:
    expected = set(COLUMNS[kind])
    mapped = tuple(
        HEADER_ALIASES.get(header.strip().upper())
        or re.sub(r"_+", "_", re.sub(r"[\s-]+", "_", header.strip().upper()))
        for header in headers
    )
    unknown = set(mapped) - expected
    if unknown:
        raise ValueError(f"Unknown {kind} columns in {path}: {', '.join(sorted(unknown))}")
    if len(mapped) != len(set(mapped)):
        raise ValueError(f"Headers map to the same column in {path}")
    return mapped
